package test:test;

interface handler-interface {
    record request {
        uri: string
    }

    handleevent: func(event: request) -> request;
}

world handler-world {
    export handler-interface;
}